services:
  - type: web
    name: sweettogether
    runtime: dotnet
    repo: https://github.com/sweettogether/sweettogether
    branch: master
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/SweetTogether.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
